title: Unlock6 Blog
author: Do Juhyeon

navbar-links:
  Home: ""
  Blog: "posts"
  About: "about"
  Contact: "contact"

avatar: "/assets/img/profile.png"
round-avatar: true

social-network-links:
  github: unlock6
  email: ""
rss-description: Personal blog & portfolio

share-links-active:
  twitter: false
  facebook: false
  linkedin: false

url-pretty: "unlock6.github.io"

title-on-all-pages: true

excerpt_length: 40
feed_show_excerpt: true
feed_show_tags: false

post_search: false
edit_page_button: false

# ---- Color Style: White & Minimal ----
page-col: "#FFFFFF"
text-col: "#1C1C1C"
link-col: "#0072F5"
hover-col: "#005FCC"
navbar-col: "#FFFFFF"
navbar-text-col: "#1C1C1C"
navbar-border-col: "#E9E9E9"
footer-col: "#FFFFFF"
footer-text-col: "#9E9E9E"
footer-link-col: "#1C1C1C"
footer-hover-col: "#0072F5"

timezone: "Asia/Seoul"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 6

kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-sitemap
